export const avatars = [
  {
    name: 'Avatar 1',
    imageUrl: '/products/avatar1.avif',
    storageId: 'kg26mhbz9e8jpjpgktw1ftf6a57r2k1t',
  },
  {
    name: 'Avatar 2',
    imageUrl: '/products/avatar2.webp',
    storageId: 'kg28q8wr4me05qn6mnbjfbe9qd7r2met',
  },
  {
    name: 'Avatar 3',
    imageUrl: '/products/avatar3.avif',
    storageId: 'kg2464nsb07ad18czf8w2evb3x7r2vew',
  },
  {
    name: 'Avatar 4',
    imageUrl: '/products/avatar4.webp',
    storageId: 'kg225213e6nrbehg2f7bksfs6n7r2xan',
  },
  {
    name: 'Avatar 5',
    imageUrl: '/products/avatar5.webp',
    storageId: 'kg22qp611nb3gmb5bjrs1ega9n7r2cys',
  },
  {
    name: 'Avatar 6',
    imageUrl: '/products/avatar6.webp',
    storageId: 'kg278q1td5tekc7bdgcpj2080d7r3q7c',
  },
]

export const sampleProduct = [
  {
    name: 'headphone',
    imageUrl: '/products/headphone.png',
    storageId: 'kg23jn89wm4gj02rcsd8t4p1rx7r6fwn',
  },
  {
    name: 'juice can',
    imageUrl: '/products/juice-can.png',
    storageId: 'kg2bqkrrpcswss91hd47mdz8z17r6c4z',
  },
  {
    name: 'perfume',
    imageUrl: '/products/perfume2.png',
    storageId: 'kg2dr4cct54m5vv7vaknp795457r7q53',
  },
  {
    name: 'burger',
    imageUrl: '/products/burger.png',
    storageId: 'kg23ny4bv1b9h9pdk8h0tg3ykd7r72kd',
  },
  {
    name: 'ice cream',
    imageUrl: '/products/ice-creame.png',
    storageId: 'kg27kfpr2wanta0t4vzgz412xh7r67gy',
  },
]

export const promptVariations = {
  randomAiStory: [
    "a video on an original time-travel adventure story with unexpected plot twists",
    "a video on a futuristic story about AI consciousness and human connection",
    "a video on a space exploration story with alien encounters and cosmic mysteries",
    "a video on a cyberpunk story set in a dystopian digital world",
    "a video on a fantasy story about magical creatures in a hidden realm",
    "a video on a post-apocalyptic survival story with hope and redemption",
    "a video on a steampunk adventure with Victorian-era technology and airships",
    "a video on a parallel universe story where physics work differently",
    "a video on a robot rebellion story with themes of freedom and identity",
    "a video on an underwater civilization discovering the surface world",
    "a video on a story about humans living inside a massive virtual reality",
    "a video on a telepathic society where thoughts become visible",
    "a video on a world where emotions control the weather patterns",
    "a video on a colony ship story with generational conflicts in deep space",
    "a video on a story about digital ghosts haunting social media platforms",
    "a video on a bioluminescent forest world with sentient plant life",
    "a video on a dimension-hopping adventure through infinite realities",
    "a video on a story about memory merchants who trade in experiences",
    "a video on a world where gravity flows upward instead of downward",
    "a video on a story about color thieves in a monochrome future",
    "a video on a nano-world adventure inside the human bloodstream",
    "a video on a story about dream architects building sleeping realities",
    "a video on a floating city story above toxic clouds",
    "a video on a story about shapeshifters hiding in plain sight",
    "a video on a world where music has magical properties",
    "a video on a story about genetic memory and inherited skills",
    "a video on a crystal cave civilization with light-based technology",
    "a video on a story about sentient shadows seeking independence",
    "a video on a world where aging happens in reverse",
    "a video on a story about pocket dimensions hidden in everyday objects",
    "a video on a magnetic levitation city with floating transportation",
    "a video on a story about symbiotic aliens bonding with humans",
    "a video on a world where seasons last for decades",
    "a video on a story about digital archaeologists exploring data ruins",
    "a video on a bio-mechanical world where organic and tech merge",
    "a video on a story about quantum entangled twins across galaxies",
    "a video on a world where silence is a valuable currency",
    "a video on a story about holographic historians preserving the past",
    "a video on a underground civilization powered by geothermal energy",
    "a video on a story about empathic healers who absorb pain",
    "a video on a world where thoughts crystallize into physical objects",
    "a video on a story about interdimensional mail delivery service",
    "a video on a gaseous planet where beings exist as living storms",
    "a video on a story about time photographers capturing moments",
    "a video on a world where every person has a visible aura",
    "a video on a story about mechanical birds carrying encrypted messages",
    "a video on a desert planet with sand-swimming nomads",
    "a video on a story about consciousness uploading gone wrong",
    "a video on a world where plants control human behavior",
    "a video on a story about asteroid miners discovering ancient artifacts",
    "a video on a frozen world with thermal underground cities",
    "a video on a story about probability manipulators changing odds",
    "a video on a world where mathematics becomes physical reality",
    "a video on a story about psionic warriors battling mind parasites",
    "a video on a cloud city with weather-controlling technology",
    "a video on a story about genetic artists sculpting living beings",
    "a video on a world where books write themselves",
    "a video on a story about holographic families in digital homes",
    "a video on a tree-city civilization with branch-highways",
    "a video on a story about emotion vampires feeding on feelings",
    "a video on a world where colors have different physical properties",
    "a video on a story about quantum mechanics repair technicians",
    "a video on a mirror dimension where everything is reversed",
    "a video on a story about space-time cartographers mapping reality",
    "a video on a world where gravity varies by location",
    "a video on a story about sentient viruses achieving consciousness",
    "a video on a crystal planet with geometric life forms",
    "a video on a story about dream police investigating nightmares",
    "a video on a world where sound creates visible architecture",
    "a video on a story about interdimensional refugees seeking asylum",
    "a video on a mechanical world with clockwork inhabitants",
    "a video on a story about telepathic plants forming a network",
    "a video on a world where seasons are controlled by emotions",
    "a video on a story about quantum archaeologists digging through time",
    "a video on a living spaceship with biological corridors",
    "a video on a story about gravity artists sculpting with weightlessness",
    "a video on a world where memories can be physically extracted",
    "a video on a story about digital ghosts haunting smart devices",
    "a video on a plasma-based civilization existing in star cores",
    "a video on a story about genetic time-locks hiding future abilities",
    "a video on a world where every thought creates a butterfly effect",
    "a video on a story about morphing cities that rebuild themselves",
    "a video on a ice planet with aurora-powered technology",
    "a video on a story about consciousness pirates hijacking minds",
    "a video on a world where language shapes physical reality",
    "a video on a story about nano-civilization living in computer circuits",
    "a video on a volcanic world with lava-surfing inhabitants",
    "a video on a story about temporal mechanics fixing timeline breaks",
    "a video on a world where evolution happens in real-time",
    "a video on a story about sentient weapons choosing their wielders",
    "a video on a gas giant with floating jellyfish cities",
    "a video on a story about reality programmers debugging existence",
    "a video on a world where empathy is a physical force",
    "a video on a story about interdimensional bounty hunters",
    "a video on a micro-world existing between atoms",
    "a video on a story about genetic musicians composing with DNA",
    "a video on a world where darkness and light are living entities",
    "a video on a story about probability farmers growing chance",
    "a video on a tidal-locked planet with eternal day and night sides",
    "a video on a story about memory thieves stealing experiences",
    "a video on a world where stories become real when told",
    "a video on a story about quantum entangled lovers across dimensions",
    "a video on a fungal network world with spore-based communication",
    "a video on a story about time detectives solving temporal crimes",
    "a video on a world where every person has a unique superpower"
  ],
  scaryStay: [
    "a video on a haunted house story with mysterious disappearances",
    "a video on an urban legend about cursed objects and their victims",
    "a video on a psychological horror story involving mind games and reality distortion",
    "a video on a supernatural story about restless spirits seeking justice",
    "a video on a creepy folklore tale from ancient cultures with dark magic",
    "a video on a modern ghost story set in abandoned locations",
    "a video on a body horror story with mysterious transformations",
    "a video on a possessed doll that terrorizes a family",
    "a video on a haunted elevator that traps people between floors",
    "a video on a cursed mirror that shows alternate realities",
    "a video on a shape-shifting creature stalking a small town",
    "a video on a haunted smartphone that sends messages from the dead",
    "a video on a sleep paralysis demon that becomes increasingly real",
    "a video on a haunted painting that changes when no one's looking",
    "a video on a phantom hitchhiker who appears on lonely roads",
    "a video on a cursed music box that plays deadly melodies",
    "a video on a vengeful spirit trapped in an old photograph",
    "a video on a demonic possession story in a modern apartment",
    "a video on a haunted video game that affects real life",
    "a video on a shadow person that feeds on human fear",
    "a video on a cursed antique shop where items have dark histories",
    "a video on a poltergeist that communicates through social media",
    "a video on a haunted hospital where patients never truly leave",
    "a video on a demonic entity living in the dark web",
    "a video on a cursed cemetery where the dead don't rest",
    "a video on a phantom train that appears at midnight crossings",
    "a video on a haunted basement that exists in multiple dimensions",
    "a video on a malevolent AI that haunts smart home systems",
    "a video on a cursed book that writes itself with blood",
    "a video on a ghostly figure that appears in security footage",
    "a video on a haunted theater where performances never end",
    "a video on a demonic presence in a children's playground",
    "a video on a cursed wedding dress that dooms brides",
    "a video on a phantom caller that predicts death",
    "a video on a haunted car that drives itself to crime scenes",
    "a video on a supernatural entity living in electrical outlets",
    "a video on a cursed recipe that poisons anyone who cooks it",
    "a video on a ghostly child that appears in family photos",
    "a video on a haunted webcam that shows other dimensions",
    "a video on a demonic presence in a seemingly innocent garden",
    "a video on a cursed jewelry box that steals souls",
    "a video on a phantom smell that leads to horrific discoveries",
    "a video on a haunted basement freezer that preserves the living",
    "a video on a malevolent spirit that lives in reflection pools",
    "a video on a cursed typewriter that types death sentences",
    "a video on a ghostly figure that haunts video calls",
    "a video on a haunted dollhouse that recreates real tragedies",
    "a video on a demonic entity that feeds on digital interactions",
    "a video on a cursed family heirloom that brings misfortune",
    "a video on a phantom bus that picks up the living",
    "a video on a haunted storage unit filled with cursed belongings",
    "a video on a supernatural presence in an abandoned amusement park",
    "a video on a cursed simulation that traps consciousness",
    "a video on a ghostly accountant that audits people's lives",
    "a video on a haunted smart watch that counts down to death",
    "a video on a demonic presence in a virtual reality headset",
    "a video on a cursed social media filter that changes reality",
    "a video on a phantom delivery driver that brings cursed packages",
    "a video on a haunted streaming service that shows personal nightmares",
    "a video on a supernatural entity that lives in WiFi signals",
    "a video on a cursed playlist that drives listeners insane",
    "a video on a ghostly figure that appears in drone footage",
    "a video on a haunted GPS that leads drivers to their doom",
    "a video on a demonic presence in a food delivery app",
    "a video on a cursed cryptocurrency that costs more than money",
    "a video on a phantom gamer that haunts online matches",
    "a video on a haunted dating app that matches with the dead",
    "a video on a supernatural presence in a meditation app",
    "a video on a cursed fitness tracker that monitors your soul",
    "a video on a ghostly figure that appears in home security systems",
    "a video on a haunted voice assistant that obeys darker commands",
    "a video on a demonic entity living in cloud storage",
    "a video on a cursed translation app that speaks in tongues",
    "a video on a phantom rideshare driver that never reaches destinations",
    "a video on a haunted email account that sends messages to hell",
    "a video on a supernatural presence in a banking app",
    "a video on a cursed weather app that controls local climate",
    "a video on a ghostly figure that haunts video conferencing",
    "a video on a haunted shopping app that delivers cursed items",
    "a video on a demonic presence in a sleep tracking app",
    "a video on a cursed map application that shows parallel worlds",
    "a video on a phantom photographer that appears in selfies",
    "a video on a haunted news app that reports future tragedies",
    "a video on a supernatural entity living in password managers",
    "a video on a cursed messaging app that sends texts to the dead",
    "a video on a ghostly presence in a recipe app",
    "a video on a haunted calendar that schedules supernatural events",
    "a video on a demonic entity in a language learning app",
    "a video on a cursed meditation timer that opens portals",
    "a video on a phantom presence in a flashlight app",
    "a video on a haunted calculator that computes life expectancy",
    "a video on a supernatural entity in a note-taking app",
    "a video on a cursed alarm clock that wakes the dead",
    "a video on a ghostly figure in a photo editing app",
    "a video on a haunted compass that points to the underworld",
    "a video on a demonic presence in a barcode scanner",
    "a video on a cursed level meter that measures spiritual energy",
    "a video on a phantom entity in a magnifying glass app",
    "a video on a haunted unit converter that converts souls",
    "a video on a supernatural presence in a QR code reader",
    "a video on a cursed stopwatch that freezes time permanently",
    "a video on a ghostly figure in a color picker app",
    "a video on a haunted ruler app that measures life spans"
  ],
  historicalFacts: [
    "a video on fascinating ancient civilizations and their mysterious disappearances",
    "a video on legendary historical figures and their incredible achievements",
    "a video on pivotal moments that changed the course of world history",
    "a video on ancient inventions that were ahead of their time",
    "a video on historical mysteries that remain unsolved to this day",
    "a video on forgotten empires and their remarkable discoveries",
    "a video on historical events that seem too strange to be true",
    "a video on the mysterious construction techniques of ancient pyramids",
    "a video on lost cities that were rediscovered centuries later",
    "a video on ancient medical practices that actually worked",
    "a video on historical figures who lived double lives",
    "a video on ancient trade routes that connected distant civilizations",
    "a video on mysterious historical documents with unknown origins",
    "a video on ancient astronomical knowledge that amazes scientists today",
    "a video on historical plagues that shaped human evolution",
    "a video on forgotten languages that held secrets of the past",
    "a video on ancient navigation techniques used by early explorers",
    "a video on historical weather events that changed civilization",
    "a video on mysterious ancient artifacts found in wrong time periods",
    "a video on historical figures who predicted modern technology",
    "a video on ancient burial practices and their cultural significance",
    "a video on historical battles decided by unexpected factors",
    "a video on ancient food preservation methods still used today",
    "a video on mysterious historical disappearances of entire populations",
    "a video on ancient architectural marvels that defy explanation",
    "a video on historical figures who changed their names and identities",
    "a video on ancient mining techniques that created underground cities",
    "a video on historical natural disasters that reshaped continents",
    "a video on mysterious ancient symbols found worldwide",
    "a video on historical figures who lived extraordinarily long lives",
    "a video on ancient transportation methods across impossible terrain",
    "a video on historical treaties that prevented major wars",
    "a video on ancient manufacturing techniques lost to time",
    "a video on mysterious historical photographs with unexplained elements",
    "a video on historical figures who mastered multiple fields of study",
    "a video on ancient communication systems across vast distances",
    "a video on historical expeditions that ended in mystery",
    "a video on ancient energy sources that powered great civilizations",
    "a video on mysterious historical coincidences that seem impossible",
    "a video on historical figures who influenced multiple cultures",
    "a video on ancient preservation techniques that protected knowledge",
    "a video on historical migrations that populated entire continents",
    "a video on ancient entertainment forms that captivated civilizations",
    "a video on mysterious historical time capsules and their contents",
    "a video on historical figures who lived through multiple centuries",
    "a video on ancient metallurgy techniques creating superior alloys",
    "a video on historical natural phenomena that terrified ancient peoples",
    "a video on ancient educational systems that produced great minds",
    "a video on mysterious historical maps showing unknown lands",
    "a video on historical figures who communicated with future generations",
    "a video on ancient agricultural innovations that fed great civilizations",
    "a video on historical religious ceremonies with scientific purposes",
    "a video on ancient textile techniques creating impossible patterns",
    "a video on mysterious historical sounds recorded in ancient sites",
    "a video on historical figures who influenced art across cultures",
    "a video on ancient water management systems in desert regions",
    "a video on historical astronomical events that changed beliefs",
    "a video on ancient surgical procedures with modern precision",
    "a video on mysterious historical lights seen across the sky",
    "a video on historical figures who connected distant continents",
    "a video on ancient mathematical discoveries ahead of their time",
    "a video on historical animals that influenced human development",
    "a video on ancient chemical processes creating lasting materials",
    "a video on mysterious historical voices heard in empty places",
    "a video on historical figures who mastered multiple languages",
    "a video on ancient optical illusions built into architecture",
    "a video on historical geological events that preserved ancient life",
    "a video on ancient musical instruments with impossible acoustics",
    "a video on mysterious historical footprints in stone",
    "a video on historical figures who predicted their own futures",
    "a video on ancient heating systems in freezing climates",
    "a video on historical botanical discoveries that changed medicine",
    "a video on ancient artistic techniques creating lasting colors",
    "a video on mysterious historical objects that change temperature",
    "a video on historical figures who influenced multiple generations",
    "a video on ancient warfare tactics that are still studied today",
    "a video on historical meteorological events recorded in art",
    "a video on ancient philosophical concepts proven by modern science",
    "a video on mysterious historical structures aligned with stars",
    "a video on historical figures who communicated through codes",
    "a video on ancient transportation systems through mountain ranges",
    "a video on historical biological specimens preserved in amber",
    "a video on ancient mechanical devices with complex functions",
    "a video on mysterious historical temperature anomalies in artifacts",
    "a video on historical figures who influenced technological development",
    "a video on ancient storage systems preserving organic materials",
    "a video on historical seismic events recorded in ancient texts",
    "a video on ancient psychological techniques for mental training",
    "a video on mysterious historical magnetic anomalies in sites",
    "a video on historical figures who bridged scientific disciplines",
    "a video on ancient ecological management preventing environmental collapse",
    "a video on historical atmospheric events visible in ice cores",
    "a video on ancient spiritual practices with measurable effects",
    "a video on mysterious historical electrical phenomena in artifacts",
    "a video on historical figures who documented future technologies",
    "a video on ancient crystalline structures with unknown properties",
    "a video on historical biological mutations recorded in art",
    "a video on ancient geometric principles in sacred architecture",
    "a video on mysterious historical radiation signatures in objects",
    "a video on historical figures who influenced multiple scientific fields",
    "a video on ancient photographic techniques before cameras existed",
    "a video on historical quantum effects observed in ancient experiments",
    "a video on ancient holographic principles in artistic techniques"
  ],
  bedTimeStory: [
    "a video on a gentle story about forest animals helping each other through seasons",
    "a video on a magical tale of a child who befriends stars and moon creatures",
    "a video on a cozy story about a sleepy village where dreams come alive",
    "a video on an adventure story about brave toys protecting their sleeping child",
    "a video on a peaceful tale of underwater friends in a coral reef kingdom",
    "a video on a heartwarming story about a magical garden that grows kindness",
    "a video on a soothing tale of cloud shepherds guiding dreams across the sky",
    "a video on a gentle story about a teddy bear's journey to comfort scared children",
    "a video on a magical tale of fireflies lighting the way home for lost creatures",
    "a video on a cozy story about a bookworm dragon who tells bedtime stories",
    "a video on a peaceful tale of sleepy pandas sharing bamboo dreams",
    "a video on a heartwarming story about a lighthouse keeper's friendship with whales",
    "a video on a soothing tale of musical flowers singing lullabies to butterflies",
    "a video on a gentle story about a sleepy train carrying dream passengers",
    "a video on a magical tale of rainbow bridges connecting sleeping children's rooms",
    "a video on a cozy story about a bakery cat who makes midnight treats for mice",
    "a video on a peaceful tale of sleepy owls hosting forest tea parties",
    "a video on a heartwarming story about a snow globe village coming alive at night",
    "a video on a soothing tale of gentle giants who tuck mountains into bed",
    "a video on a gentle story about a sleepy lighthouse beam painting aurora dreams",
    "a video on a magical tale of dream catchers weaving stories in the wind",
    "a video on a cozy story about a clockmaker's toys dancing at midnight",
    "a video on a peaceful tale of sleepy sea turtles carrying island dreams",
    "a video on a heartwarming story about a quilt that wraps the world in comfort",
    "a video on a soothing tale of sleepy elephants painting sunset clouds",
    "a video on a gentle story about a music box ballerina's nighttime adventures",
    "a video on a magical tale of shooting stars delivering bedtime wishes",
    "a video on a cozy story about a sleepy library where books read themselves",
    "a video on a peaceful tale of dream boats sailing on pillow seas",
    "a video on a heartwarming story about a sleepy volcano that warms cold mountains",
    "a video on a soothing tale of gentle dinosaurs who guard children's dreams",
    "a video on a gentle story about a sleepy ice cream truck that visits dream towns",
    "a video on a magical tale of pocket dragons who live in pajama pockets",
    "a video on a cozy story about a sleepy mailman delivering letters to the moon",
    "a video on a peaceful tale of dream fish swimming in starlight rivers",
    "a video on a heartwarming story about a sleepy garden gnome's magical helpers",
    "a video on a soothing tale of gentle robots who repair broken dreams",
    "a video on a gentle story about a sleepy carousel horse's magical night rides",
    "a video on a magical tale of lullaby birds nesting in children's hair",
    "a video on a cozy story about a sleepy baker who makes cloud bread",
    "a video on a peaceful tale of dream butterflies carrying wishes to heaven",
    "a video on a heartwarming story about a sleepy wizard's apprentice learning kindness",
    "a video on a soothing tale of gentle mermaids who sing to sleeping whales",
    "a video on a gentle story about a sleepy artist who paints dreams on cave walls",
    "a video on a magical tale of cuddle monsters who protect children from nightmares",
    "a video on a cozy story about a sleepy inventor creating happiness machines",
    "a video on a peaceful tale of dream kites flying through sleeping cities",
    "a video on a heartwarming story about a sleepy shepherd counting cloud sheep",
    "a video on a soothing tale of gentle spiders who weave comfort blankets",
    "a video on a gentle story about a sleepy musician composing lullabies for planets",
    "a video on a magical tale of wish flowers that bloom only at bedtime",
    "a video on a cozy story about a sleepy photographer capturing sweet dreams",
    "a video on a peaceful tale of dream trains carrying sleepy passengers to wonderland",
    "a video on a heartwarming story about a sleepy gardener growing pillow plants",
    "a video on a soothing tale of gentle winds that whisper bedtime stories",
    "a video on a gentle story about a sleepy carpenter building treehouses for fairies",
    "a video on a magical tale of snuggle bears who hug away bad dreams",
    "a video on a cozy story about a sleepy chef cooking dreams in star kitchens",
    "a video on a peaceful tale of lullaby rivers flowing through sleeping forests",
    "a video on a heartwarming story about a sleepy postman delivering dreams",
    "a video on a soothing tale of gentle aliens who teach earthlings about peace",
    "a video on a gentle story about a sleepy dancer twirling through moonbeam ballrooms",
    "a video on a magical tale of comfort quilts that travel to lonely children",
    "a video on a cozy story about a sleepy scientist discovering the formula for happiness",
    "a video on a peaceful tale of dream dolphins swimming through aurora oceans",
    "a video on a heartwarming story about a sleepy teacher reading to forest creatures",
    "a video on a soothing tale of gentle time travelers bringing bedtime stories from future",
    "a video on a gentle story about a sleepy architect building castles in the clouds",
    "a video on a magical tale of bedtime fairies sprinkling sleep dust on flowers",
    "a video on a cozy story about a sleepy explorer discovering islands made of pillows",
    "a video on a peaceful tale of dream painters coloring the night sky",
    "a video on a heartwarming story about a sleepy magician whose tricks bring joy",
    "a video on a soothing tale of gentle monsters who are actually very shy",
    "a video on a gentle story about a sleepy sailor navigating seas of hot chocolate",
    "a video on a magical tale of bedtime angels who watch over sleeping animals",
    "a video on a cozy story about a sleepy detective solving the mystery of missing socks",
    "a video on a peaceful tale of dream merchants selling bottled happiness",
    "a video on a heartwarming story about a sleepy farmer growing fields of sweet dreams",
    "a video on a soothing tale of gentle pirates who search for treasure chests of smiles",
    "a video on a gentle story about a sleepy tailor sewing clothes for dream creatures",
    "a video on a magical tale of comfort clouds that rain gentle hugs",
    "a video on a cozy story about a sleepy veterinarian caring for imaginary pets",
    "a video on a peaceful tale of dream mechanics fixing broken imagination machines",
    "a video on a heartwarming story about a sleepy conductor directing orchestras of crickets",
    "a video on a soothing tale of gentle knights who protect the kingdom of dreams",
    "a video on a gentle story about a sleepy florist arranging bouquets of starlight",
    "a video on a magical tale of bedtime storytellers who live inside picture books",
    "a video on a cozy story about a sleepy janitor cleaning up scattered dreams",
    "a video on a peaceful tale of comfort creatures who live under children's beds",
    "a video on a heartwarming story about a sleepy watchmaker whose clocks tell dream time",
    "a video on a soothing tale of gentle astronomers who name stars after sleeping children",
    "a video on a gentle story about a sleepy philosopher pondering the meaning of cuddles",
    "a video on a magical tale of dream weavers creating tapestries of children's adventures",
    "a video on a cozy story about a sleepy librarian organizing books by dream categories",
    "a video on a peaceful tale of lullaby composers writing songs for sleepy planets",
    "a video on a heartwarming story about a sleepy zookeeper caring for dream animals",
    "a video on a soothing tale of gentle archaeologists discovering ancient bedtime stories",
    "a video on a gentle story about a sleepy meteorologist predicting rainbow weather",
    "a video on a magical tale of comfort ambassadors bringing peace between dream kingdoms",
    "a video on a cozy story about a sleepy translator speaking the language of snores",
    "a video on a peaceful tale of dream cartographers mapping the geography of sleep"
  ],
  motivational: [
    "a video on an inspiring story of someone overcoming physical limitations to achieve greatness",
    "a video on a motivational tale about turning failure into the foundation of success",
    "a video on an uplifting story about community support changing someone's life",
    "a video on an encouraging narrative about discovering hidden talents later in life",
    "a video on an inspiring journey from poverty to making a positive global impact",
    "a video on a motivational story about resilience during life's toughest challenges",
    "a video on an uplifting tale about following dreams despite all odds",
    "a video on an inspiring story of a person who transformed their fear into courage",
    "a video on a motivational tale about turning a personal tragedy into helping others",
    "a video on an uplifting story of someone who never gave up on their education",
    "a video on an encouraging narrative about breaking generational cycles of limitation",
    "a video on an inspiring journey of someone who rebuilt their life after losing everything",
    "a video on a motivational story about finding purpose through helping strangers",
    "a video on an uplifting tale of a person who turned their weakness into strength",
    "a video on an inspiring story of someone who achieved success without formal training",
    "a video on a motivational tale about a person who started a movement from their bedroom",
    "a video on an uplifting story of someone who learned to read at age 40",
    "a video on an encouraging narrative about turning social anxiety into public speaking mastery",
    "a video on an inspiring journey of someone who lost 200 pounds and kept it off",
    "a video on a motivational story about a person who built a business from $50",
    "a video on an uplifting tale of someone who overcame addiction to help others recover",
    "a video on an inspiring story of a person who changed careers at 60 and thrived",
    "a video on a motivational tale about turning childhood trauma into healing others",
    "a video on an uplifting story of someone who learned 10 languages as an adult",
    "a video on an encouraging narrative about overcoming imposter syndrome",
    "a video on an inspiring journey from homeless to helping the homeless",
    "a video on a motivational story about a person who turned rejection into motivation",
    "a video on an uplifting tale of someone who started exercising at 70",
    "a video on an inspiring story of a person who taught themselves to code and changed their life",
    "a video on a motivational tale about overcoming social isolation to build community",
    "a video on an uplifting story of someone who turned their disability into their superpower",
    "a video on an encouraging narrative about finding love after heartbreak",
    "a video on an inspiring journey from bankruptcy to financial freedom",
    "a video on a motivational story about a person who overcame their fear of water to become a swimmer",
    "a video on an uplifting tale of someone who returned to school as a grandparent",
    "a video on an inspiring story of a person who turned their stutter into becoming a motivational speaker",
    "a video on a motivational tale about overcoming perfectionism to achieve success",
    "a video on an uplifting story of someone who built confidence after years of bullying",
    "a video on an encouraging narrative about turning depression into purpose",
    "a video on an inspiring journey from being fired to becoming an entrepreneur",
    "a video on a motivational story about a person who learned to forgive their worst enemy",
    "a video on an uplifting tale of someone who overcame chronic illness to inspire others",
    "a video on an inspiring story of a person who turned their mistakes into wisdom",
    "a video on a motivational tale about overcoming the fear of public speaking",
    "a video on an uplifting story of someone who found their calling in their darkest hour",
    "a video on an encouraging narrative about building self-worth from nothing",
    "a video on an inspiring journey from people-pleasing to authentic living",
    "a video on a motivational story about a person who overcame gambling addiction",
    "a video on an uplifting tale of someone who learned to love themselves first",
    "a video on an inspiring story of a person who turned loneliness into helping others connect",
    "a video on a motivational tale about overcoming the fear of failure",
    "a video on an uplifting story of someone who found strength in vulnerability",
    "a video on an encouraging narrative about turning anger into positive action",
    "a video on an inspiring journey from procrastination to productivity mastery",
    "a video on a motivational story about a person who overcame their fear of heights",
    "a video on an uplifting tale of someone who turned their sensitivity into empathy leadership",
    "a video on an inspiring story of a person who learned to set boundaries and thrive",
    "a video on a motivational tale about overcoming the need for external validation",
    "a video on an uplifting story of someone who found peace after years of chaos",
    "a video on an encouraging narrative about turning comparison into inspiration",
    "a video on an inspiring journey from perfectionism paralysis to imperfect action",
    "a video on a motivational story about a person who overcame their fear of technology",
    "a video on an uplifting tale of someone who turned their pessimism into realistic optimism",
    "a video on an inspiring story of a person who learned to trust again after betrayal",
    "a video on a motivational tale about overcoming the fear of being alone",
    "a video on an uplifting story of someone who found joy in simple pleasures",
    "a video on an encouraging narrative about turning negative self-talk into self-compassion",
    "a video on an inspiring journey from workaholic to work-life balance",
    "a video on a motivational story about a person who overcame their fear of commitment",
    "a video on an uplifting tale of someone who turned their introversion into a superpower",
    "a video on an inspiring story of a person who learned to ask for help",
    "a video on a motivational tale about overcoming the fear of change",
    "a video on an uplifting story of someone who found purpose in their pain",
    "a video on an encouraging narrative about turning jealousy into admiration",
    "a video on an inspiring journey from control freak to letting go",
    "a video on a motivational story about a person who overcame their fear of success",
    "a video on an uplifting tale of someone who turned their shyness into authentic connection",
    "a video on an inspiring story of a person who learned to celebrate small wins",
    "a video on a motivational tale about overcoming the fear of being judged",
    "a video on an uplifting story of someone who found strength in admitting weakness",
    "a video on an encouraging narrative about turning resentment into forgiveness",
    "a video on an inspiring journey from people-pleaser to boundary-setter",
    "a video on a motivational story about a person who overcame their fear of aging",
    "a video on an uplifting tale of someone who turned their anxiety into mindfulness",
    "a video on an inspiring story of a person who learned to receive love",
    "a video on a motivational tale about overcoming the fear of not being enough",
    "a video on an uplifting story of someone who found courage in their vulnerability",
    "a video on an encouraging narrative about turning regret into wisdom",
    "a video on an inspiring journey from victim mentality to empowerment",
    "a video on a motivational story about a person who overcame their fear of intimacy",
    "a video on an uplifting tale of someone who turned their isolation into solitude",
    "a video on an inspiring story of a person who learned to trust their intuition",
    "a video on a motivational tale about overcoming the fear of disappointing others",
    "a video on an uplifting story of someone who found peace with their past",
    "a video on an encouraging narrative about turning criticism into growth",
    "a video on an inspiring journey from scarcity mindset to abundance thinking",
    "a video on a motivational story about a person who overcame their fear of vulnerability",
    "a video on an uplifting tale of someone who turned their overthinking into strategic planning",
    "a video on an inspiring story of a person who learned to embrace uncertainty",
    "a video on a motivational tale about overcoming the fear of being ordinary",
    "a video on an uplifting story of someone who found extraordinary in the mundane",
    "a video on an encouraging narrative about turning pessimism into hope",
    "a video on an inspiring journey from reactive living to intentional choices",
    "a video on a motivational story about a person who overcame their fear of being seen",
    "a video on an uplifting tale of someone who turned their people-pleasing into authentic kindness",
    "a video on an inspiring story of a person who learned to celebrate others' success",
    "a video on a motivational tale about overcoming the fear of starting over",
    "a video on an uplifting story of someone who found strength in asking questions",
    "a video on an encouraging narrative about turning self-doubt into self-awareness",
    "a video on an inspiring journey from external validation to internal worth",
    "a video on a motivational story about a person who overcame their fear of conflict",
    "a video on an uplifting tale of someone who turned their restlessness into adventure",
    "a video on an inspiring story of a person who learned to enjoy the journey not just destinations",
    "a video on a motivational tale about overcoming the fear of being different",
    "a video on an uplifting story of someone who found beauty in their scars",
    "a video on an encouraging narrative about turning impatience into persistence",
    "a video on an inspiring journey from closed-minded to growth-oriented thinking"
  ],
  funFacts: [
    "a video on incredible facts about the human body and its amazing capabilities",
    "a video on mind-blowing facts about ocean depths and mysterious sea creatures",
    "a video on fascinating facts about space phenomena and cosmic wonders",
    "a video on amazing facts about animal intelligence and surprising behaviors",
    "a video on incredible facts about ancient technologies and engineering marvels",
    "a video on surprising facts about everyday objects and their hidden secrets",
    "a video on astonishing facts about weather phenomena and natural disasters",
    "a video on mind-blowing facts about quantum physics and particle behavior",
    "a video on incredible facts about plant intelligence and communication",
    "a video on fascinating facts about insect societies and their complex systems",
    "a video on amazing facts about human memory and brain plasticity",
    "a video on surprising facts about the speed of light and time dilation",
    "a video on astonishing facts about volcanic activity and geological forces",
    "a video on mind-blowing facts about DNA and genetic inheritance",
    "a video on incredible facts about bird migration and navigation systems",
    "a video on fascinating facts about crystal formation and mineral properties",
    "a video on amazing facts about sound waves and acoustic phenomena",
    "a video on surprising facts about gravity and its mysterious properties",
    "a video on astonishing facts about bacterial intelligence and adaptation",
    "a video on mind-blowing facts about magnetic fields and electromagnetic forces",
    "a video on incredible facts about sleep cycles and dream patterns",
    "a video on fascinating facts about photosynthesis and energy conversion",
    "a video on amazing facts about animal camouflage and adaptation strategies",
    "a video on surprising facts about water molecules and their unique properties",
    "a video on astonishing facts about black holes and space-time distortion",
    "a video on mind-blowing facts about cellular regeneration and healing",
    "a video on incredible facts about symbiotic relationships in nature",
    "a video on fascinating facts about atmospheric pressure and weather systems",
    "a video on amazing facts about electrical impulses in living organisms",
    "a video on surprising facts about mathematical patterns in nature",
    "a video on astonishing facts about deep-sea pressure and adaptation",
    "a video on mind-blowing facts about chemical reactions in everyday life",
    "a video on incredible facts about animal communication across species",
    "a video on fascinating facts about thermal dynamics and heat transfer",
    "a video on amazing facts about evolutionary adaptations over time",
    "a video on surprising facts about optical illusions and visual perception",
    "a video on astonishing facts about radioactive decay and atomic structure",
    "a video on mind-blowing facts about ecosystem interconnections and food webs",
    "a video on incredible facts about mechanical advantage and simple machines",
    "a video on fascinating facts about color perception and light wavelengths",
    "a video on amazing facts about migration patterns and animal navigation",
    "a video on surprising facts about chemical bonds and molecular structure",
    "a video on astonishing facts about geological time scales and fossil formation",
    "a video on mind-blowing facts about neuroplasticity and brain adaptation",
    "a video on incredible facts about pollination systems and plant reproduction",
    "a video on fascinating facts about seismic activity and earthquake prediction",
    "a video on amazing facts about genetic mutations and species diversity",
    "a video on surprising facts about atmospheric composition and breathing",
    "a video on astonishing facts about cellular division and growth patterns",
    "a video on mind-blowing facts about electromagnetic spectrum and radiation",
    "a video on incredible facts about predator-prey relationships and population control",
    "a video on fascinating facts about molecular motion and temperature",
    "a video on amazing facts about adaptation to extreme environments",
    "a video on surprising facts about light pollution and astronomical observation",
    "a video on astonishing facts about chemical pH and acid-base reactions",
    "a video on mind-blowing facts about tissue regeneration and healing processes",
    "a video on incredible facts about animal intelligence and problem-solving abilities",
    "a video on fascinating facts about pressure systems and weather forecasting",
    "a video on amazing facts about genetic expression and environmental triggers",
    "a video on surprising facts about orbital mechanics and planetary motion",
    "a video on astonishing facts about enzyme function and biological catalysts",
    "a video on mind-blowing facts about ecosystem services and environmental benefits",
    "a video on incredible facts about wave interference and standing wave patterns",
    "a video on fascinating facts about adaptation timescales and evolutionary pressure",
    "a video on amazing facts about atomic forces and chemical stability",
    "a video on surprising facts about biodiversity hotspots and species richness",
    "a video on astonishing facts about thermal regulation in living organisms",
    "a video on mind-blowing facts about magnetic navigation in animals",
    "a video on incredible facts about photochemical reactions and energy storage",
    "a video on fascinating facts about geological processes and rock formation",
    "a video on amazing facts about neural networks and brain connectivity",
    "a video on surprising facts about atmospheric circulation and global climate",
    "a video on astonishing facts about genetic diversity and population genetics",
    "a video on mind-blowing facts about crystalline structures and material properties",
    "a video on incredible facts about behavioral adaptations and survival strategies",
    "a video on fascinating facts about electromagnetic induction and energy generation",
    "a video on amazing facts about ecological succession and habitat development",
    "a video on surprising facts about molecular recognition and biological specificity",
    "a video on astonishing facts about tidal forces and gravitational effects",
    "a video on mind-blowing facts about metabolic pathways and energy efficiency",
    "a video on incredible facts about social behaviors and collective intelligence",
    "a video on fascinating facts about nuclear fusion and stellar energy production",
    "a video on amazing facts about immune system recognition and memory",
    "a video on surprising facts about fractal patterns and mathematical beauty in nature",
    "a video on astonishing facts about adaptation rates and environmental change",
    "a video on mind-blowing facts about quantum entanglement and particle physics",
    "a video on incredible facts about symbiotic evolution and co-adaptation",
    "a video on fascinating facts about thermodynamics and energy conservation",
    "a video on amazing facts about behavioral ecology and survival strategies",
    "a video on surprising facts about electromagnetic fields and biological effects",
    "a video on astonishing facts about population dynamics and carrying capacity",
    "a video on mind-blowing facts about chemical communication and pheromones",
    "a video on incredible facts about geological cycles and planetary processes",
    "a video on fascinating facts about neural development and brain growth",
    "a video on amazing facts about atmospheric chemistry and gas cycles",
    "a video on surprising facts about genetic regulation and development control",
    "a video on astonishing facts about physical forces and mechanical principles",
    "a video on mind-blowing facts about ecological relationships and environmental balance",
    "a video on incredible facts about molecular machines and cellular processes",
    "a video on fascinating facts about cosmic radiation and planetary protection",
    "a video on amazing facts about adaptation mechanisms and stress responses",
    "a video on surprising facts about chemical equilibrium and reaction rates"
  ]
}
